"""
Builds a real .pptx file from the JSON slide outline the LLM returns.
This is the "wow" deliverable: judges get a downloadable, openable
PowerPoint file, not just generated text.
"""
import json
import os
import uuid

from pptx import Presentation

if os.getenv("VERCEL"):
    # Vercel's deployed bundle is read-only; /tmp is writable for this invocation.
    OUTPUT_DIR = os.path.join("/tmp", "mediaforge-generated")
else:
    OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "generated")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def build_pptx(json_str: str) -> str:
    data = json.loads(json_str)
    prs = Presentation()

    # Title slide
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = data.get("title", "Presentation")
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by MediaForge AI"

    # Content slides
    bullet_layout = prs.slide_layouts[1]
    for s in data.get("slides", []):
        slide = prs.slides.add_slide(bullet_layout)
        slide.shapes.title.text = s.get("heading", "")
        bullets = s.get("bullets", [])
        body = slide.placeholders[1].text_frame
        body.clear()
        for i, b in enumerate(bullets):
            if i == 0:
                body.text = b
            else:
                p = body.add_paragraph()
                p.text = b
        notes = s.get("speaker_notes")
        if notes:
            slide.notes_slide.notes_text_frame.text = notes

    filename = f"presentation_{uuid.uuid4().hex[:8]}.pptx"
    path = os.path.join(OUTPUT_DIR, filename)
    prs.save(path)
    return filename
